// iso-lang-codes.cpp
// Copyright (c) 2019, zhiayang
// Licensed under the Apache License Version 2.0.

#include <string>
#include <vector>
#include <unordered_map>

namespace misc
{
	// from https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
	// but only the "Living" languages. who tf gonna make subtitles in old english?
	std::unordered_map<std::string, std::vector<std::string>> languageCodeMap = {
		{ "aar", { "Afar" } },
		{ "abk", { "Abkhazian" } },
		{ "ace", { "Achinese" } },
		{ "ach", { "Acoli" } },
		{ "ada", { "Adangme" } },
		{ "ady", { "Adyghe", "Adygei" } },
		{ "afr", { "Afrikaans" } },
		{ "ain", { "Ainu" } },
		{ "aka", { "Akan" } },
		{ "ale", { "Aleut" } },
		{ "alt", { "Southern Altai" } },
		{ "amh", { "Amharic" } },
		{ "anp", { "Angika" } },
		{ "ara", { "Arabic" } },
		{ "arg", { "Aragonese" } },
		{ "arm", { "Armenian" } },
		{ "arn", { "Mapudungun", "Mapuche" } },
		{ "arp", { "Arapaho" } },
		{ "arw", { "Arawak" } },
		{ "asm", { "Assamese" } },
		{ "ast", { "Asturian", "Bable", "Leonese", "Asturleonese" } },
		{ "ava", { "Avaric" } },
		{ "awa", { "Awadhi" } },
		{ "aym", { "Aymara" } },
		{ "aze", { "Azerbaijani" } },
		{ "bak", { "Bashkir" } },
		{ "bal", { "Baluchi" } },
		{ "bam", { "Bambara" } },
		{ "ban", { "Balinese" } },
		{ "baq", { "Basque" } },
		{ "bas", { "Basa" } },
		{ "bej", { "Beja", "Bedawiyet" } },
		{ "bel", { "Belarusian" } },
		{ "bem", { "Bemba" } },
		{ "ben", { "Bengali" } },
		{ "bho", { "Bhojpuri" } },
		{ "bik", { "Bikol" } },
		{ "bin", { "Bini", "Edo" } },
		{ "bis", { "Bislama" } },
		{ "bla", { "Siksika" } },
		{ "bos", { "Bosnian" } },
		{ "bra", { "Braj" } },
		{ "bre", { "Breton" } },
		{ "bua", { "Buriat" } },
		{ "bug", { "Buginese" } },
		{ "bul", { "Bulgarian" } },
		{ "byn", { "Blin", "Bilin" } },
		{ "cad", { "Caddo" } },
		{ "car", { "Galibi Carib" } },
		{ "cat", { "Catalan", "Valencian" } },
		{ "ceb", { "Cebuano" } },
		{ "ces", { "Czech" } },
		{ "cha", { "Chamorro" } },
		{ "che", { "Chechen" } },
		{ "chk", { "Chuukese" } },
		{ "chm", { "Mari" } },
		{ "chn", { "Chinook jargon" } },
		{ "cho", { "Choctaw" } },
		{ "chp", { "Chipewyan", "Dene Suline" } },
		{ "chr", { "Cherokee" } },
		{ "chv", { "Chuvash" } },
		{ "chy", { "Cheyenne" } },
		{ "cnr", { "Montenegrin" } },
		{ "cor", { "Cornish" } },
		{ "cos", { "Corsican" } },
		{ "cre", { "Cree" } },
		{ "crh", { "Crimean Tatar", "Crimean Turkish" } },
		{ "csb", { "Kashubian" } },
		{ "cze", { "Czech" } },
		{ "dak", { "Dakota" } },
		{ "dan", { "Danish" } },
		{ "dar", { "Dargwa" } },
		{ "del", { "Delaware" } },
		{ "den", { "Slave (Athapascan)" } },
		{ "deu", { "German" } },
		{ "dgr", { "Dogrib" } },
		{ "din", { "Dinka" } },
		{ "div", { "Divehi", "Dhivehi", "Maldivian" } },
		{ "doi", { "Dogri" } },
		{ "dsb", { "Lower Sorbian" } },
		{ "dua", { "Duala" } },
		{ "dyu", { "Dyula" } },
		{ "dzo", { "Dzongkha" } },
		{ "efi", { "Efik" } },
		{ "eka", { "Ekajuk" } },
		{ "eng", { "English" } },
		{ "est", { "Estonian" } },
		{ "eus", { "Basque" } },
		{ "ewe", { "Ewe" } },
		{ "ewo", { "Ewondo" } },
		{ "fan", { "Fang" } },
		{ "fao", { "Faroese" } },
		{ "fat", { "Fanti" } },
		{ "fij", { "Fijian" } },
		{ "fil", { "Filipino", "Pilipino" } },
		{ "fin", { "Finnish" } },
		{ "fon", { "Fon" } },
		{ "fra", { "French" } },
		{ "fre", { "French" } },
		{ "frr", { "Northern Frisian" } },
		{ "frs", { "Eastern Frisian" } },
		{ "fry", { "Western Frisian" } },
		{ "ful", { "Fulah" } },
		{ "fur", { "Friulian" } },
		{ "gaa", { "Ga" } },
		{ "gay", { "Gayo" } },
		{ "gba", { "Gbaya" } },
		{ "ger", { "German" } },
		{ "gil", { "Gilbertese" } },
		{ "gla", { "Gaelic", "Scottish Gaelic" } },
		{ "gle", { "Irish" } },
		{ "glg", { "Galician" } },
		{ "glv", { "Manx" } },
		{ "gon", { "Gondi" } },
		{ "gor", { "Gorontalo" } },
		{ "grb", { "Grebo" } },
		{ "gre", { "Greek" } },
		{ "ell", { "Greek" } },
		{ "grn", { "Guarani" } },
		{ "gsw", { "Swiss German", "Alemannic", "Alsatian" } },
		{ "guj", { "Gujarati" } },
		{ "gwi", { "Gwich'in" } },
		{ "hai", { "Haida" } },
		{ "hat", { "Haitian", "Haitian Creole" } },
		{ "hau", { "Hausa" } },
		{ "haw", { "Hawaiian" } },
		{ "heb", { "Hebrew" } },
		{ "her", { "Herero" } },
		{ "hil", { "Hiligaynon" } },
		{ "hin", { "Hindi" } },
		{ "hmn", { "Hmong", "Mong" } },
		{ "hmo", { "Hiri Motu" } },
		{ "hrv", { "Croatian" } },
		{ "hsb", { "Upper Sorbian" } },
		{ "hun", { "Hungarian" } },
		{ "hup", { "Hupa" } },
		{ "hye", { "Armenian" } },
		{ "iba", { "Iban" } },
		{ "ibo", { "Igbo" } },
		{ "iii", { "Sichuan Yi", "Nuosu" } },
		{ "iku", { "Inuktitut" } },
		{ "ilo", { "Iloko" } },
		{ "ind", { "Indonesian" } },
		{ "inh", { "Ingush" } },
		{ "ipk", { "Inupiaq" } },
		{ "isl", { "Icelandic" } },
		{ "ice", { "Icelandic" } },
		{ "ita", { "Italian" } },
		{ "jav", { "Javanese" } },
		{ "jpn", { "Japanese" } },
		{ "jpr", { "Judeo-Persian" } },
		{ "jrb", { "Judeo-Arabic" } },
		{ "kaa", { "Kara-Kalpak" } },
		{ "kab", { "Kabyle" } },
		{ "kac", { "Kachin; Jingpho" } },
		{ "kal", { "Kalaallisut", "Greenlandic" } },
		{ "kam", { "Kamba" } },
		{ "kan", { "Kannada" } },
		{ "kas", { "Kashmiri" } },
		{ "kat", { "Georgian" } },
		{ "geo", { "Georgian" } },
		{ "kau", { "Kanuri" } },
		{ "kaz", { "Kazakh" } },
		{ "kbd", { "Kabardian" } },
		{ "kha", { "Khasi" } },
		{ "khm", { "Central Khmer" } },
		{ "kik", { "Kikuyu", "Gikuyu" } },
		{ "kin", { "Kinyarwanda" } },
		{ "kir", { "Kirghiz", "Kyrgyz" } },
		{ "kmb", { "Kimbundu" } },
		{ "kok", { "Konkani" } },
		{ "kom", { "Komi" } },
		{ "kon", { "Kongo" } },
		{ "kor", { "Korean" } },
		{ "kos", { "Kosraean" } },
		{ "kpe", { "Kpelle" } },
		{ "krc", { "Karachay-Balkar" } },
		{ "krl", { "Karelian" } },
		{ "kru", { "Kurukh" } },
		{ "kua", { "Kuanyama", "Kwanyama" } },
		{ "kum", { "Kumyk" } },
		{ "kur", { "Kurdish" } },
		{ "kut", { "Kutenai" } },
		{ "lad", { "Ladino" } },
		{ "lah", { "Lahnda" } },
		{ "lam", { "Lamba" } },
		{ "lao", { "Lao" } },
		{ "lav", { "Latvian" } },
		{ "lez", { "Lezghian" } },
		{ "lim", { "Limburgan", "Limburger", "Limburgish" } },
		{ "lin", { "Lingala" } },
		{ "lit", { "Lithuanian" } },
		{ "lol", { "Mongo" } },
		{ "loz", { "Lozi" } },
		{ "ltz", { "Luxembourgish", "Letzeburgesch" } },
		{ "lua", { "Luba-Lulua" } },
		{ "lub", { "Luba-Katanga" } },
		{ "lug", { "Ganda" } },
		{ "lun", { "Lunda" } },
		{ "luo", { "Luo (Kenya and Tanzania)" } },
		{ "lus", { "Lushai" } },
		{ "mad", { "Madurese" } },
		{ "mag", { "Magahi" } },
		{ "mah", { "Marshallese" } },
		{ "mai", { "Maithili" } },
		{ "mak", { "Makasar" } },
		{ "mal", { "Malayalam" } },
		{ "man", { "Mandingo" } },
		{ "mar", { "Marathi" } },
		{ "mas", { "Masai" } },
		{ "mdf", { "Moksha" } },
		{ "mdr", { "Mandar" } },
		{ "men", { "Mende" } },
		{ "mic", { "Mi'kmaq", "Micmac" } },
		{ "min", { "Minangkabau" } },
		{ "mkd", { "Macedonian" } },
		{ "mac", { "Macedonian" } },
		{ "mlg", { "Malagasy" } },
		{ "mlt", { "Maltese" } },
		{ "mnc", { "Manchu" } },
		{ "mni", { "Manipuri" } },
		{ "moh", { "Mohawk" } },
		{ "mon", { "Mongolian" } },
		{ "mos", { "Mossi" } },
		{ "mri", { "Maori" } },
		{ "mao", { "Maori" } },
		{ "msa", { "Malay" } },
		{ "may", { "Malay" } },
		{ "mus", { "Creek" } },
		{ "mwl", { "Mirandese" } },
		{ "mwr", { "Marwari" } },
		{ "mya", { "Burmese" } },
		{ "bur", { "Burmese" } },
		{ "myv", { "Erzya" } },
		{ "nap", { "Neapolitan" } },
		{ "nau", { "Nauru" } },
		{ "nav", { "Navajo", "Navaho" } },
		{ "nbl", { "Ndebele", "South Ndebele" } },
		{ "nde", { "Ndebele", "North Ndebele" } },
		{ "ndo", { "Ndonga" } },
		{ "nds", { "Low German", "Low Saxon", "German", "Saxon" } },
		{ "nep", { "Nepali" } },
		{ "new", { "Nepal Bhasa; Newari" } },
		{ "nia", { "Nias" } },
		{ "niu", { "Niuean" } },
		{ "nld", { "Dutch", "Flemish" } },
		{ "dut", { "Dutch", "Flemish" } },
		{ "nno", { "Norwegian Nynorsk", "Nynorsk", "Norwegian" } },
		{ "nob", { "Bokmål", "Norwegian", "Norwegian Bokmål" } },
		{ "nog", { "Nogai" } },
		{ "nor", { "Norwegian" } },
		{ "nqo", { "N'Ko" } },
		{ "nso", { "Pedi; Sepedi; Northern Sotho" } },
		{ "nya", { "Chichewa", "Chewa", "Nyanja" } },
		{ "nym", { "Nyamwezi" } },
		{ "nyn", { "Nyankole" } },
		{ "nyo", { "Nyoro" } },
		{ "nzi", { "Nzima" } },
		{ "oci", { "Occitan", "Provençal" } },
		{ "oji", { "Ojibwa" } },
		{ "ori", { "Oriya" } },
		{ "orm", { "Oromo" } },
		{ "osa", { "Osage" } },
		{ "oss", { "Ossetian; Ossetic" } },
		{ "pag", { "Pangasinan" } },
		{ "pam", { "Pampanga; Kapampangan" } },
		{ "pan", { "Panjabi; Punjabi" } },
		{ "pap", { "Papiamento" } },
		{ "pau", { "Palauan" } },
		{ "per", { "Persian" } },
		{ "fas", { "Persian" } },
		{ "pol", { "Polish" } },
		{ "pon", { "Pohnpeian" } },
		{ "por", { "Portuguese" } },
		{ "pus", { "Pushto; Pashto" } },
		{ "que", { "Quechua" } },
		{ "raj", { "Rajasthani" } },
		{ "rap", { "Rapanui" } },
		{ "rar", { "Rarotongan; Cook Islands Maori" } },
		{ "roh", { "Romansh" } },
		{ "rom", { "Romany" } },
		{ "rum", { "Romanian", "Moldavian", "Moldovan"	} },
		{ "ron", { "Romanian", "Moldavian", "Moldovan"	} },
		{ "run", { "Rundi" } },
		{ "rup", { "Aromanian", "Arumanian", "Macedo-Romanian" } },
		{ "rus", { "Russian" } },
		{ "sad", { "Sandawe" } },
		{ "sag", { "Sango" } },
		{ "sah", { "Yakut" } },
		{ "sas", { "Sasak" } },
		{ "sat", { "Santali" } },
		{ "scn", { "Sicilian" } },
		{ "sco", { "Scots" } },
		{ "sel", { "Selkup" } },
		{ "shn", { "Shan" } },
		{ "sid", { "Sidamo" } },
		{ "sin", { "Sinhala", "Sinhalese" } },
		{ "slo", { "Slovak" } },
		{ "slk", { "Slovak" } },
		{ "slv", { "Slovenian" } },
		{ "sma", { "Southern Sami" } },
		{ "sme", { "Northern Sami" } },
		{ "smj", { "Lule Sami" } },
		{ "smn", { "Inari Sami" } },
		{ "smo", { "Samoan" } },
		{ "sms", { "Skolt Sami" } },
		{ "sna", { "Shona" } },
		{ "snd", { "Sindhi" } },
		{ "snk", { "Soninke" } },
		{ "som", { "Somali" } },
		{ "sot", { "Sotho, Southern" } },
		{ "spa", { "Spanish; Castilian" } },
		{ "sqi", { "Albanian" } },
		{ "alb", { "Albanian" } },
		{ "srd", { "Sardinian" } },
		{ "srn", { "Sranan Tongo" } },
		{ "srp", { "Serbian" } },
		{ "srr", { "Serer" } },
		{ "ssw", { "Swati" } },
		{ "suk", { "Sukuma" } },
		{ "sun", { "Sundanese" } },
		{ "sus", { "Susu" } },
		{ "swa", { "Swahili" } },
		{ "swe", { "Swedish" } },
		{ "syr", { "Syriac" } },
		{ "tah", { "Tahitian" } },
		{ "tam", { "Tamil" } },
		{ "tat", { "Tatar" } },
		{ "tel", { "Telugu" } },
		{ "tem", { "Timne" } },
		{ "ter", { "Tereno" } },
		{ "tet", { "Tetum" } },
		{ "tgk", { "Tajik" } },
		{ "tgl", { "Tagalog" } },
		{ "tha", { "Thai" } },
		{ "tib", { "Tibetan" } },
		{ "bod", { "Tibetan" } },
		{ "tig", { "Tigre" } },
		{ "tir", { "Tigrinya" } },
		{ "tiv", { "Tiv" } },
		{ "tkl", { "Tokelau" } },
		{ "tli", { "Tlingit" } },
		{ "tmh", { "Tamashek" } },
		{ "tog", { "Tonga (Nyasa)" } },
		{ "ton", { "Tonga (Tonga Islands)" } },
		{ "tpi", { "Tok Pisin" } },
		{ "tsi", { "Tsimshian" } },
		{ "tsn", { "Tswana" } },
		{ "tso", { "Tsonga" } },
		{ "tuk", { "Turkmen" } },
		{ "tum", { "Tumbuka" } },
		{ "tur", { "Turkish" } },
		{ "tvl", { "Tuvalu" } },
		{ "twi", { "Twi" } },
		{ "tyv", { "Tuvinian" } },
		{ "udm", { "Udmurt" } },
		{ "uig", { "Uighur", "Uyghur" } },
		{ "ukr", { "Ukrainian" } },
		{ "umb", { "Umbundu" } },
		{ "urd", { "Urdu" } },
		{ "uzb", { "Uzbek" } },
		{ "vai", { "Vai" } },
		{ "ven", { "Venda" } },
		{ "vie", { "Vietnamese" } },
		{ "vot", { "Votic" } },
		{ "wal", { "Wolaitta", "Wolaytta" } },
		{ "war", { "Waray" } },
		{ "was", { "Washo" } },
		{ "wel", { "Welsh" } },
		{ "cym", { "Welsh" } },
		{ "wln", { "Walloon" } },
		{ "wol", { "Wolof" } },
		{ "xal", { "Kalmyk; Oirat" } },
		{ "xho", { "Xhosa" } },
		{ "yao", { "Yao" } },
		{ "yap", { "Yapese" } },
		{ "yid", { "Yiddish" } },
		{ "yor", { "Yoruba" } },
		{ "zap", { "Zapotec" } },
		{ "zen", { "Zenaga" } },
		{ "zgh", { "Standard Moroccan Tamazight" } },
		{ "zha", { "Zhuang", "Chuang" } },
		{ "zho", { "Chinese" } },
		{ "chi", { "Chinese" } },
		{ "zul", { "Zulu" } },
		{ "zun", { "Zuni" } },
		{ "zza", { "Zaza" } },
	};
}
